# Generated by Django 3.0.6 on 2020-05-25 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lobby', '0004_auto_20200525_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_state', models.CharField(max_length=1000)),
                ('max_to_win', models.IntegerField(default=4)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connectquatro_boards', to='lobby.Game')),
            ],
        ),
    ]
