# Generated by Django 3.0.6 on 2020-05-29 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectquatro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='board_length_x',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='board',
            name='board_length_y',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='board',
            name='max_players',
            field=models.IntegerField(default=2),
        ),
    ]
