# Generated by Django 3.0.6 on 2020-05-30 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connectquatro', '0002_auto_20200529_0252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='max_players',
        ),
    ]
