# Generated by Django 3.0.6 on 2020-05-30 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0008_auto_20200530_1931'),
        ('connectquatro', '0003_remove_board_max_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='game',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lobby.Game'),
        ),
    ]
