# Generated by Django 3.0.6 on 2020-05-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0003_auto_20200525_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
