# Generated by Django 3.0.6 on 2020-05-26 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0004_auto_20200525_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_lobby_owner',
            field=models.BooleanField(default=False),
        ),
    ]
