# Generated by Django 3.0.6 on 2020-05-27 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0005_player_is_lobby_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='name',
            field=models.CharField(default='', max_length=24),
            preserve_default=False,
        ),
    ]
