# Generated by Django 3.0.6 on 2020-05-29 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0006_game_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='turn_order',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
