# Generated by Django 3.0.6 on 2020-05-30 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0007_player_turn_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='is_full',
        ),
        migrations.AddField(
            model_name='game',
            name='max_players',
            field=models.IntegerField(default=2),
        ),
    ]
