# Generated by Django 3.0.6 on 2020-05-31 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0009_player_lobby_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('connectquat', 'Connect-Quat'), ('texasholdem', "Texas Hold'Em")], max_length=24),
        ),
    ]
