# Generated by Django 3.0.6 on 2020-06-01 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0010_auto_20200531_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='color',
            field=models.CharField(blank=True, choices=[('#a80000', 'Red'), ('#c78500', 'Orange'), ('#918d00', 'Yellow'), ('#00803c', 'Green'), ('#0039bf', 'Blue'), ('#6b4b9c', 'Purple'), ('#787878', 'Gray'), ('#5c4300', 'Brown')], default=None, max_length=8, null=True),
        ),
    ]
