# Generated by Django 3.0.6 on 2020-06-02 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0011_player_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_over',
            field=models.BooleanField(default=False),
        ),
    ]
