# Generated by Django 3.0.6 on 2020-06-03 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0012_game_is_over'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='archived_players',
            field=models.ManyToManyField(related_name='archived_players', to='lobby.Player'),
        ),
    ]
