# Generated by Django 3.0.6 on 2020-06-03 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0013_game_archived_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='archived_players',
            field=models.ManyToManyField(related_name='archived_games', to='lobby.Player'),
        ),
    ]
