# Generated by Django 3.0.6 on 2020-06-05 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0014_auto_20200603_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winners', models.CharField(default='<< DRAW >>', max_length=255)),
                ('game', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lobby.Game')),
            ],
        ),
    ]
