# Generated by Django 3.0.6 on 2020-06-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0015_completedgame'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedgame',
            name='winners',
        ),
        migrations.AddField(
            model_name='completedgame',
            name='winners',
            field=models.ManyToManyField(to='lobby.Player'),
        ),
    ]
