# Generated by Django 3.0.6 on 2020-06-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0016_auto_20200605_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='join_game_id',
            field=models.CharField(blank=True, default=None, max_length=55, null=True),
        ),
    ]
