# Generated by Django 3.0.6 on 2020-06-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0017_game_join_game_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='tick_count',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
