# Generated by Django 3.0.6 on 2020-06-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0018_game_tick_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='max_seconds_per_turn',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
