# Generated by Django 3.0.6 on 2020-06-07 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0020_gamefeedmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='is_ready',
        ),
        migrations.AlterField(
            model_name='gamefeedmessage',
            name='message_type',
            field=models.CharField(choices=[('move-dc', 'Player Dropped A Chip'), ('move-check', 'Player Checks'), ('move-call', 'Player Calls'), ('move-raise', 'Player Raises'), ('move-fold', 'Player Folds'), ('quit', 'Player Quit'), ('status', 'Game Status')], max_length=10),
        ),
    ]
