# Generated by Django 3.0.6 on 2020-06-07 23:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0022_auto_20200607_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedgame',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='completedgame',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
